### ISSUE TITLE
entire menu is gone

### ISSUE THREAD

**Issue by airbutbackwards** [EladNLG/ModSettings#2]
game is stuck on windowed, so i dont know if that might be the cause (cant fix it because i cant see the menu)
but yeah entire menu is gone
![image](https://user-images.githubusercontent.com/102485961/184559386-d794438e-656d-44d6-b698-ab76408b17fe.png)

**Comment by airbutbackwards** [comment]
![image](https://user-images.githubusercontent.com/102485961/184559430-e37c7b19-6ceb-4f4b-8d8d-8fd31d830547.png)
nevermind, the menu is just gone

**Comment by EladNLG** [comment]
need logs or I can't help
