### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Hazuzy** [EladNLG/ModSettings#3]
How  can  i   use   it  in  the   Titanfall 2？not   Northstar，Need to change  something？I'm new hands in the write code，thanks

**Comment by EladNLG** [comment]
Not usable without Northstar.

**Comment by Hazuzy** [comment]
well，If we  can  used custom server framework？I used this，But there's no way to use Settings in officially with it，It's like it's not installed

**Comment by Hazuzy** [comment]
I heard that some code should be modified, but I don't know how to modify it，if   we  want  to  using  in   Titanfall 2
